version: "3"

services:
  # app:
  # image: clojure:latest
  # command: >
  # bash -c "cd /app && java -jar target/ixn-0.1.1.jar"
  # ports:
  # - "3300:3300"
  # volumes:
  # - .:/app
  # depends_on:
  # - db
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    networks:
      - ixn
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "ixnsecret"
      POSTGRES_DB: "ixn"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    networks:
      - ixn
    environment:
      PGADMIN_DEFAULT_EMAIL: "thijs.creemers@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "2#4Thscr"

volumes:
  pgdata:

networks:
  ixn:
