version: "3"

services:
  # app:
  # image: clojure:latest
  # command: >
  # bash -c "cd /app && java -jar target/ixn-0.1.1.jar"
  # ports:
  # - "3300:3300"
  # volumes:
  # - .:/app
  # depends_on:
  # - db
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    env_file:
      - .env # The name of your environment file (the one at the repository root)

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    env_file:
      - .env # The name of your environment file (the one at the repository root)
